language: bash

sudo: false

node_js:
  - "4.1"

env:
  global:
    - REPO="osvalr/docker-odoo-image"
    - VERSION="master"
install:
  - npm install -g dockerlint

script:
  - cd ${TRAVIS_BUILD_DIR} && ./.dlint.sh
