language: python

sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

node_js:
  - "4.1"

virtualenv:
  system_site_packages: true

install:
  - npm install -g validate-dockerfile

script:
  - for dfile in `find ${HOME}/build/osvalr/docker-odoo-image -name 'Dockerfile' -not -path "./.git/*"`; do echo "[ CHECKING $dfile ]"; docklint $dfile && echo ""; done
